// Design tokens — generated by hand from design/tokens.json (source of truth).
// Do not use raw hex/pt values in widgets; add tokens here instead.
// Spec: docs/design-system.md Part A.

import 'package:flutter/cupertino.dart';

abstract final class AppColors {
  // Brand — coral ramp (identity accent)
  static const primary = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFFF5A4E),
    darkColor: Color(0xFFFF6B5F),
  );
  static const primaryPressed = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFE64A3F),
    darkColor: Color(0xFFFF8177),
  );
  static const tint12 = CupertinoDynamicColor.withBrightness(
    color: Color(0x1FFF5A4E),
    darkColor: Color(0x29FF6B5F),
  );
  static const tint24 = CupertinoDynamicColor.withBrightness(
    color: Color(0x3DFF5A4E),
    darkColor: Color(0x47FF6B5F),
  );
  static const onPrimary = Color(0xFFFFFFFF);

  // Status — SOS is always the hot systemRed, never coral
  static const sos = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFD70015),
    darkColor: Color(0xFFFF453A),
  );
  static const sosBg = CupertinoDynamicColor.withBrightness(
    color: Color(0x1AD70015),
    darkColor: Color(0x2EFF453A),
  );
  static const success = CupertinoDynamicColor.withBrightness(
    color: Color(0xFF34C759),
    darkColor: Color(0xFF30D158),
  );
  static const warning = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFFF9F0A),
    darkColor: Color(0xFFFFD60A),
  );
  static const info = CupertinoDynamicColor.withBrightness(
    color: Color(0xFF007AFF),
    darkColor: Color(0xFF0A84FF),
  );

  // Neutrals & surfaces
  static const bgBase = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFF2F2F7),
    darkColor: Color(0xFF000000),
  );
  static const bgElevated = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFFFFFFF),
    darkColor: Color(0xFF1C1C1E),
  );
  static const bgSecondary = CupertinoDynamicColor.withBrightness(
    color: Color(0xFFFFFFFF),
    darkColor: Color(0xFF2C2C2E),
  );
  static const fillTertiary = CupertinoDynamicColor.withBrightness(
    color: Color(0x1F767680),
    darkColor: Color(0x3D767680),
  );
  static const separator = CupertinoDynamicColor.withBrightness(
    color: Color(0x4A3C3C43),
    darkColor: Color(0x99545458),
  );
  static const textPrimary = CupertinoDynamicColor.withBrightness(
    color: Color(0xFF000000),
    darkColor: Color(0xFFFFFFFF),
  );
  static const textSecondary = CupertinoDynamicColor.withBrightness(
    color: Color(0x993C3C43),
    darkColor: Color(0x99EBEBF5),
  );
  static const textTertiary = CupertinoDynamicColor.withBrightness(
    color: Color(0x4D3C3C43),
    darkColor: Color(0x4DEBEBF5),
  );
}

abstract final class AppSpace {
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
}

abstract final class AppRadius {
  static const double s = 10;
  static const double m = 16;
  static const double l = 24;
  static const double pill = 999;
}

abstract final class AppLayout {
  static const double margin = 16;
  static const double gutter = 12;
  static const double listGap = 8;
  static const double minTap = 44;
  static const double navBarHeight = 44;
  static const double tabBarHeight = 49;
}

abstract final class Glass {
  static const double regularBlur = 24;
  static const double thinBlur = 16;
  static const double saturation = 1.8;
  static const double regularFillOpacity = 0.55;
  static const double thinFillOpacityLight = 0.35;
  static const double thinFillOpacityDark = 0.40;
}

abstract final class AppMotion {
  static const quick = Duration(milliseconds: 200);
  static const standard = Duration(milliseconds: 300);
}
