import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:uuid/uuid.dart';

import 'models.dart';

part 'db.g.dart';

const _uuid = Uuid();

/// One row per medication. The schedule is folded in (one schedule per med,
/// simpler than the spec's separate DoseSchedule entity — revisit if a med
/// ever needs multiple schedules).
class Medications extends Table {
  TextColumn get id => text().clientDefault(_uuid.v4)();
  TextColumn get name => text()();
  TextColumn get strength => text().withDefault(const Constant(''))();
  TextColumn get form => textEnum<MedForm>()();
  TextColumn get instructions => text().withDefault(const Constant(''))();

  TextColumn get scheduleType => textEnum<ScheduleType>()();

  /// Comma-separated minutes-since-midnight, e.g. "480,780,1200".
  /// Used by [ScheduleType.timesOfDay] and [ScheduleType.weekdays].
  TextColumn get doseTimes => text().withDefault(const Constant(''))();
  IntColumn get intervalHours => integer().nullable()();

  /// Bitmask Mon=1 … Sun=64. Used by [ScheduleType.weekdays].
  IntColumn get weekdaysMask => integer().nullable()();

  DateTimeColumn get startDate => dateTime()();
  DateTimeColumn get endDate => dateTime().nullable()();

  // SOS fields (used from M2; schema ready now).
  BoolColumn get isSos => boolean().withDefault(const Constant(false))();
  IntColumn get maxPerDay => integer().nullable()();
  IntColumn get minGapMinutes => integer().nullable()();

  IntColumn get stockCount => integer().nullable()();
  DateTimeColumn get archivedAt => dateTime().nullable()();
  DateTimeColumn get createdAt => dateTime().clientDefault(DateTime.now)();

  @override
  Set<Column> get primaryKey => {id};
}

/// Materialized dose occurrences (~7 days ahead), generated by DoseGenerator.
class DoseInstances extends Table {
  TextColumn get id => text().clientDefault(_uuid.v4)();
  TextColumn get medicationId => text().references(Medications, #id)();
  DateTimeColumn get scheduledAt => dateTime()();
  TextColumn get status => textEnum<DoseStatus>()
      .withDefault(Constant(DoseStatus.upcoming.name))();
  DateTimeColumn get actionAt => dateTime().nullable()();
  DateTimeColumn get snoozedUntil => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<Set<Column>> get uniqueKeys => [
        {medicationId, scheduledAt},
      ];
}

/// Immutable history — survives medication archive/delete.
@DataClassName('MedicationLogEntry')
class MedicationLogEntries extends Table {
  TextColumn get id => text().clientDefault(_uuid.v4)();
  TextColumn get medicationId => text()();
  TextColumn get medicationName => text()();
  TextColumn get doseInstanceId => text().nullable()();
  DateTimeColumn get scheduledAt => dateTime().nullable()();
  DateTimeColumn get actualAt => dateTime()();
  TextColumn get status => textEnum<LogStatus>()();
  TextColumn get note => text().withDefault(const Constant(''))();

  @override
  Set<Column> get primaryKey => {id};
}

@DriftDatabase(tables: [Medications, DoseInstances, MedicationLogEntries])
class AppDb extends _$AppDb {
  AppDb() : super(driftDatabase(name: 'medlog'));

  AppDb.forTesting(super.e);

  @override
  int get schemaVersion => 1;

  // --- Medications -----------------------------------------------------

  Stream<List<Medication>> watchActiveMedications() => (select(medications)
        ..where((m) => m.archivedAt.isNull())
        ..orderBy([(m) => OrderingTerm.asc(m.name)]))
      .watch();

  Future<Medication?> getMedication(String id) =>
      (select(medications)..where((m) => m.id.equals(id))).getSingleOrNull();

  Future<void> upsertMedication(MedicationsCompanion entry) =>
      into(medications).insertOnConflictUpdate(entry);

  /// Archive (never hard-delete: log history references it, spec §4.5).
  Future<void> archiveMedication(String id) async {
    await (update(medications)..where((m) => m.id.equals(id)))
        .write(MedicationsCompanion(archivedAt: Value(DateTime.now())));
    await (delete(doseInstances)
          ..where((d) =>
              d.medicationId.equals(id) &
              d.status.equalsValue(DoseStatus.upcoming)))
        .go();
  }

  // --- Dose instances ----------------------------------------------------

  Stream<List<DoseInstance>> watchDosesBetween(DateTime from, DateTime to) =>
      (select(doseInstances)
            ..where((d) => d.scheduledAt.isBetweenValues(from, to))
            ..orderBy([(d) => OrderingTerm.asc(d.scheduledAt)]))
          .watch();

  Future<List<DoseInstance>> upcomingDoses(DateTime from) =>
      (select(doseInstances)
            ..where((d) =>
                d.status.equalsValue(DoseStatus.upcoming) &
                d.scheduledAt.isBiggerOrEqualValue(from))
            ..orderBy([(d) => OrderingTerm.asc(d.scheduledAt)]))
          .get();

  Future<void> setDoseStatus(
    String doseId,
    DoseStatus status, {
    DateTime? actionAt,
  }) =>
      (update(doseInstances)..where((d) => d.id.equals(doseId))).write(
        DoseInstancesCompanion(
          status: Value(status),
          actionAt: Value(actionAt),
        ),
      );

  Future<void> snoozeDose(String doseId, DateTime until) =>
      (update(doseInstances)..where((d) => d.id.equals(doseId))).write(
        DoseInstancesCompanion(snoozedUntil: Value(until)),
      );

  // --- Log ---------------------------------------------------------------

  Future<void> addLogEntry(MedicationLogEntriesCompanion entry) =>
      into(medicationLogEntries).insert(entry);

  Stream<List<MedicationLogEntry>> watchRecentLog(int limit) =>
      (select(medicationLogEntries)
            ..orderBy([(l) => OrderingTerm.desc(l.actualAt)])
            ..limit(limit))
          .watch();
}
